### ISSUE TITLE
**Скласти інтро**

### ISSUE THREAD

**Issue by pixel-pixel** [pixel-pixel/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by not-a-pixel-pixel** [comment]
Декілька фактів про мене:
1) я лінивий
2)

**Comment by not-a-pixel-pixel** [comment]
> Декілька фактів про мене:
> 
> 1. я лінивий
