### ISSUE TITLE
**Скласти блок контактної інформації**

### ISSUE THREAD

**Issue by pixel-pixel** [pixel-pixel/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by not-a-pixel-pixel** [comment]
Андрій Бартіш
Взагалі, мама радила не розкидуватись своїми даними направо-наліво, а якщо вже так хочете зв'язатися зі мною і запросити на роботу, то кричіть. У мене хороший слух, я почую.
